project_name: env2file
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers:
  - image_templates:
      - southclaws/env2file:latest
    dockerfile: Dockerfile
nfpms:
  - vendor: Southclaws
    homepage: https://github.com/Southclaws/env2file
    maintainer: Southclaws <hello@southcla.ws>
    description: A tiny utility for turning environment variable values into files.
    license: GPLv3
    formats:
      - deb
